<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5tkmcgj\srcEnvDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5tkmcgj/srcEnvDebugProjectContainer.php') {
    touch(__DIR__.'/Container5tkmcgj.legacy');

    return;
}

if (!\class_exists(srcEnvDebugProjectContainer::class, false)) {
    \class_alias(\Container5tkmcgj\srcEnvDebugProjectContainer::class, srcEnvDebugProjectContainer::class, false);
}

return new \Container5tkmcgj\srcEnvDebugProjectContainer(array(
    'container.build_hash' => '5tkmcgj',
    'container.build_id' => 'ee0142a8',
    'container.build_time' => 1516699677,
));
