<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAfugn3t\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAfugn3t/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAfugn3t.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerAfugn3t\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerAfugn3t\srcProdProjectContainer(array(
    'container.build_hash' => 'Afugn3t',
    'container.build_id' => '22ab0a47',
    'container.build_time' => 1516698601,
));
