<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.6mb_cr8' shared service.

return $this->services['service_locator.6mb_cr8'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('session' => function () {
    return ${($_ = isset($this->services['session']) ? $this->services['session'] : $this->load(__DIR__.'/getSessionService.php')) && false ?: '_'};
}));
