<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZxaaaaf\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZxaaaaf/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZxaaaaf.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZxaaaaf\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerZxaaaaf\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Zxaaaaf',
    'container.build_id' => '9f1e7030',
    'container.build_time' => 1516607704,
));
